# Generated by Django 4.2.7 on 2023-12-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id telegram'),
        ),
    ]
