# Generated by Django 4.2.7 on 2023-12-12 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='place')),
                ('time', models.TimeField(verbose_name='time')),
                ('activity', models.TextField(verbose_name='activity')),
                ('period', models.CharField(choices=[('hourly', 'Ежечасно'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно')], default='daily', max_length=50, verbose_name='period')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='reward')),
                ('time_required', models.PositiveSmallIntegerField(default=5, verbose_name='time_required')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pleasant_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pleasant_set', to='habits_app.habit')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_set', to='habits_app.habit')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
