# Generated by Django 4.2.7 on 2023-12-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_required',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='time_required'),
        ),
    ]
