# Generated by Django 4.2.7 on 2023-12-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_app', '0002_alter_habit_time_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='pleasant_habit',
        ),
        migrations.AddField(
            model_name='habit',
            name='is_pleasant',
            field=models.BooleanField(default=False, verbose_name='pleasant habit'),
        ),
    ]
